version: '3.8'

services:
  iaam-nextjs:
    image: ${ECR_REGISTRY:-localhost}/iaam-nextjs:latest
    container_name: iaam-nextjs
    restart: unless-stopped
    env_file: .env
    expose:
      - "3000"

  ssinstrument-nextjs:
    image: ${ECR_REGISTRY:-localhost}/ssinstrument-nextjs:latest
    container_name: ssinstrument-nextjs
    restart: unless-stopped
    env_file: .env
    expose:
      - "3000"
  # strapi:
  #   image: ${ECR_REGISTRY:-localhost}/strapi:latest
  #   container_name: strapi-backend
  #   restart: unless-stopped
  #   env_file: .env
  #   expose:
  #     - "1337"

strapi:
  image: ${ECR_REGISTRY:-localhost}/strapi:latest
  container_name: strapi-backend
  restart: unless-stopped

  environment:
    # Server
    HOST: 0.0.0.0
    PORT: 1337

    # Secrets
    APP_KEYS: risAZoWxzRJ1htJBMaujMw==,jGiLmhDNPzIFTdIRVQDBvg==,ytO9wTUjq8Qrr41kUFRSYg==,0FQeYxc/ulioidBiLuN+xA==
    API_TOKEN_SALT: 6iokfrw7YfUydTl0YLzQWg==
    ADMIN_JWT_SECRET: We4s9pco9gheLtzrpy/HFw==
    TRANSFER_TOKEN_SALT: 677NsWS8SfWZMQ9fmxbLRg==
    ENCRYPTION_KEY: guRrRNGaIs/wDJ54/MiPsQ==
    JWT_SECRET: 86kneR/GzOMGwScMwQI6KA==

    # Database
    DATABASE_CLIENT: postgres
    DATABASE_HOST: database-1.c5i4uiaecb64.eu-north-1.rds.amazonaws.com
    DATABASE_PORT: 5432
    DATABASE_NAME: postgres
    DATABASE_USERNAME: postgresStrpi
    DATABASE_PASSWORD: vw1ELRLLOVEO3C5ggf4H

    # ⚠️ IMPORTANT FIX (SSL ISSUE REMOVE)
    DATABASE_SSL: "false"

  expose:
    - "1337"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount Certbot certificates
      - /var/www/certbot:/var/www/certbot # Webroot for certbot renewals
    depends_on:
      - iaam-nextjs
      - ssinstrument-nextjs
      - strapi

networks:
  default:
    name: myapp_network
